### ISSUE TITLE
kraft list update 404

### ISSUE THREAD

**Issue by aiaoyang** [unikraft/kraft#104]
**Describe the bug**
when execute kraft -v list update, raise [CRITICAL] 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest"}
**To Reproduce**
run kraft list update

**Expected behavior**
update success

**Screenshots**
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/21071240/161366439-cd83a3c0-28da-497c-a5b1-f0513811053f.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 20.04

**Additional context**
github token have been create with repo:public_repo permission

**Comment by StefanJum** [comment]
Hi, please make sure that the token ONLY has the `repo:public_repo` permissions. Also make sure to export it as `UK_KRAFT_GITHUB_TOKEN` before you run `kraft list update`, or use the command `UK_KRAFT_GITHUB_TOKEN=<your_GitHub_token_here> kraft list update`.

**Comment by aiaoyang** [comment]
> Hi, please make sure that the token ONLY has the `repo:public_repo` permissions. Also make sure to export it as `UK_KRAFT_GITHUB_TOKEN` before you run `kraft list update`, or use the command `UK_KRAFT_GITHUB_TOKEN=<your_GitHub_token_here> kraft list update`.

yes, Im sure there is only repo:public_repo permission and export UK_KRAFT_GITHUB_TOKEN has been set before I execute the kraft list update command. when token is not set,  the response show this below 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/21071240/161374037-a0ef3f8c-6618-4f14-bf17-5562d7f6d9bd.png">

**Comment by ppttech** [comment]
I am experiencing the same issue. I set the env var before running `kraft list update` (of course) and only selected the `public_repo` option when creating the token.

**Comment by amirkmzh** [comment]
I have faced the same error, And I have exactly followed the tutorial.

**Comment by gabrielmocanu** [comment]
@amirkmzh @ppttech @aiaoyang 
Can you check again? Please make sure that you re-install kraft after `git pull`.

**Comment by ppttech** [comment]
@gabrielmocanu For me it is fixed now, at least `kraft list update` doesn't throw this error anymore.
Thanks!
