### ISSUE TITLE
App fails to start when binding a virtual network bridge (`could not open /dev/net/tun: No such device`)

### ISSUE THREAD

**Issue by bttger** [unikraft/kraft#117]
**Describe the bug**
The demo httpreply app fails to start when I want to bind a virtual network bridge. It works though if I just run it without bridge. The output I get is the following:

```sh
$ kraft run -b virbr0 "netdev.ipv4_addr=172.44.0.2 netdev.ipv4_gw_addr=172.44.0.1 netdev.ipv4_subnet_mask=255.255.255.0 --"     
[INFO    ] Using networking bridge 'virbr0'
Trying to get root privileges...
qemu-system-x86_64: -netdev tap,id=hnet0,vhost=off,script=/tmp/qemu-guest-19927/ifup0.sh,downscript=/tmp/qemu-guest-19927/ifdown0.sh: could not open /dev/net/tun: No such device
```

**To Reproduce**
1. Install kraft as descirbed in https://unikraft.org/docs/getting-started/
2. Create directory for the httpreply app and clone the repository into it with `kraft init -t httpreply`
3. Create a virtual bridge (see snippet below)
4. Run `kraft run -b virbr0 "netdev.ipv4_addr=172.44.0.2 netdev.ipv4_gw_addr=172.44.0.1 netdev.ipv4_subnet_mask=255.255.255.0 --"`
5. See error

```
$ sudo brctl addbr virbr0
$ sudo ip a a  172.44.0.1/24 dev virbr0
$ sudo ip l set dev virbr0 up
```
**Expected behavior**
I expect it to run without errors and the network be bridged with the host system.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: Kernel: 5.19.13-1-MANJARO
 - Arch: x86_64
 - Shell: zsh 5.9 (x86_64-pc-linux-gnu)
 - GCC: gcc (GCC) 12.2.0
 - pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)
 - Python 3.10.7
 - kraft, version 0.5.0.dev491

**Comment by bttger** [comment]
`modprobe tun` returned `modprobe: FATAL: Module tun not found in directory /lib/modules/5.19.13-1-MANJARO`

**Comment by jpetrina** [comment]
@bttger This might happen if you had updated the kernel recently, which removed the old kernel modules directory e.g. I have on my machine:
```
/lib/modules
├── 5.19.10-arch1-1
├── 5.19.13-arch1-1
├── 5.19.7-arch1-1
├── 5.19.9-arch1-1
├── 6.0.1-arch2-1
└── 6.0.2-arch1-1
```

You could try `modprobe -S <version> ...` command to try and load from the "new" version, otherwise you would have to reboot to load the new kernel.

**Comment by bttger** [comment]
Thank you @jpetrina! I updated my kernel in the morning and I didn't restart my machine yet. Issue solved after rebooting and loading the module again.
