### ISSUE TITLE
Running kraft in Docker

### ISSUE THREAD

**Issue by salerio-gs** [unikraft/kraft#13]
**Describe the bug**
I pulled the kraft package from Github with docker and tried to run it. It runs OK, but where does it put the files? Is there any doc showing how to map local directories into the container?

**Comment by nderjung** [comment]
Hi Peter,

If you do not mount the container to a directory it will only create artifacts within the container itself.

Try:
```bash
$ docker run -it --rm --name kraft \
    -e UK_WORKDIR=/usr/src/unikraft \
    -v $(pwd)/unikraft:/usr/src/unikraft \
    --entrypoint bash \
    unikraft/kraft:latest
```

Inside the container, everything will be located at `/usr/src/unikraft`.  Outside the container, this folder is mounted to `$(pwd)/unikraft`.

**Comment by salerio-gs** [comment]
Hi, many thanks. I sort of got half way to working that out but now its clear.
