### ISSUE TITLE
Can I use networking with linuxu?

### ISSUE THREAD

**Issue by sartakov** [unikraft/kraft#14]
Dear developers  

I am playing with Unikraft and wondering, is there any way to communicate with network applications (like Redis) on top of linuxu? It seems that networking is available only in a virtual environment...

Thank you

**Comment by skuenzer** [comment]
Hi,

we are in the process of upstreaming an TAP driver soon. This one will enable networking in linuxu environments.

Thanks,

Simon

**Comment by sartakov** [comment]
thanks
