### ISSUE TITLE
CLANG/LLVM support

### ISSUE THREAD

**Issue by sartakov** [unikraft/kraft#18]
Hi 

currently, the building system is based on GCC. Do you have plans to support CLANG/LLVM?

**Comment by nderjung** [comment]
Hi @sartakov,

Yes, [there is currently on-going work to support `clang`](https://patchwork.unikraft.org/patch/737480/).  When this becomes more stable it will make its way into the `kraft` tool itself via parameterization.  [This is currently planned](https://github.com/unikraft/kraft/projects/2#card-37444034).

Thanks

**Comment by sartakov** [comment]
great!
