### ISSUE TITLE
Missing dependencies "feedparser" and "semver"

### ISSUE THREAD

**Issue by nkcr** [unikraft/kraft#28]
**Describe the bug**
The kraft cli complains with `ModuleNotFoundError: No module named 'feedparser'` and `ModuleNotFoundError: No module named 'semver'` on a fresh install. 

**To Reproduce**
1. Follow the setup instructions on a fresh new Ubuntu server 20.04.1 machine
2. Run `kraft -h`

**Expected behavior**
Should see the kraft help

**Desktop (please complete the following information):**
 - OS: Ubuntu server
 - Version 20.04.1

**Additional context**
Running `pip3 install feedparser semver` solves the problem.

**Comment by nderjung** [comment]
This has been confirmed and will be released in upcoming changes.

See https://github.com/unikraft/kraft/pull/26/commits/f66b654d234302519dffc4a60abfa0ea5a5a2fad
