### ISSUE TITLE
Install issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by faerbersteve** [unikraft/kraft#34]
**Describe the bug**
The installation fails on fresh installed Ubuntu 20.04 when following the get started steps with the error:
```
Searching for appdirs
Reading https://pypi.org/simple/appdirs/
Downloading https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl#sha256=a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128
Best match: appdirs 1.4.4
Processing appdirs-1.4.4-py2.py3-none-any.whl
Installing appdirs-1.4.4-py2.py3-none-any.whl to /home/andreas/.local/lib/python3.8/site-packages
Adding appdirs 1.4.4 to easy-install.pth file

Installed /home/andreas/.local/lib/python3.8/site-packages/appdirs-1.4.4-py3.8.egg
error: requests 2.22.0 is installed but requests>=2.23.0 is required by {'cookiecutter'}
```

**To Reproduce**
```
git clone https://github.com/unikraft/kraft.git
cd kraft
python3 setup.py install --user
```

**Expected behavior**
Installation completes

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, fresh install

**Solution**
```
pip3 install requests -U
pip3 install binaryornot Jinja2 Jinja2-time poyo python-slugify
```

**Comment by nderjung** [comment]
Hi,

Please try the `staging` branch of kraft, I believe this issue has already been resolved and will be merged into stable soon.

```bash
pip3 install https://github.com/unikraft/kraft.gi@staging
```

Thanks

**Comment by faerbersteve** [comment]
Thank you
`pip3 install git+https://github.com/unikraft/kraft.git@staging`
solved it.

Now I have further issues when creating the helloworld app.
When following the two last steps of the readme (of the helloworld repo) I receive the following issue.
I added the -t in the kraft up command as it was missing.
```
user@ubuntu:~/my-first-unikernel$ kraft --verbose up -p kvm -m x86_64 -t helloworld sw
[DEBUG   ] Synchronizing cache with filesystem...
[DEBUG   ] Checking cache for staleness...
[DEBUG   ] Retrieving http://github.com/unikraft/lib-* from cache...
[DEBUG   ] Retrieving http://github.com/unikraft/plat-* from cache...
[DEBUG   ] Retrieving http://github.com/unikraft/unikraft.git from cache...
[DEBUG   ] Retrieving http://github.com/unikraft/app-* from cache...
[DEBUG   ] Using configuration files: /home/andreas/.unikraft/apps/helloworld/kraft.yaml
[CRITICAL] kraft_app_init() got an unexpected keyword argument 'template_app_version'
[CRITICAL] Traceback (most recent call last):
  File "/home/andreas/.local/lib/python3.8/site-packages/kraft/cmd/up.py", line 202, in cmd_up
    kraft_app_init(
  File "/home/andreas/.local/lib/python3.8/site-packages/click-8.0.0a1-py3.8.egg/click/decorators.py", line 18, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: kraft_app_init() got an unexpected keyword argument 'template_app_version'
```
Could you please help me further?

**Comment by nderjung** [comment]
Hi, awesome :)

Please open up a new issue where we can then work on a fix for this.  Thanks!

**Comment by faerbersteve** [comment]
Sorry, the issue is not solved in the staging branch.
I tried it again with `sudo pip3 install git+https://github.com/unikraft/kraft.git@staging` and got the same issue.

**Comment by nderjung** [comment]
Did you still have to install these dependencies manually using pip or were you running into an issue with the `kraft up` command?

**Comment by nderjung** [comment]
I ran:
```bash
$ docker run -it --rm ubuntu:20.08 bash
# now instide a container
$ apt-get update
$ apt-get install -y --no-install-recommends build-essential libncurses-dev libyaml-dev flex git wget socat bison unzip uuid-runtime; # from the README.md
$ apt-get install -y python3-pip
$ pip3 install git+https://github.com/unikraft/kraft.git@staging
$ kraft --version
kraft, version 0.4.1a0
```
and had no problems

**Comment by faerbersteve** [comment]
I am not using docker.
I run all commands in my Ubuntu 20.04 environment. 
Yes I had to install those dependencies manually. 
I received the same issue which I mentioned in my first comment

**Comment by faerbersteve** [comment]
Today I have setup a new ubuntu 20.10 vm for developing.
There the installation of kraft works fine.
It was not necessary to install the additional packages.
