### ISSUE TITLE
Kraft failes with list index out of range

### ISSUE THREAD

**Issue by gabrielmocanu** [unikraft/kraft#80]
**Describe the bug**
Right now if you are trying to run the **hello-world** application you will end up with **list index out of range** error. This can be for all applications if the name of the directory of the application is different from the name of the application from **kraft.yml**.

**To Reproduce**
1. git clone git@github.com:unikraft/app-helloworld.git
2. cd app-helloworld
3. kraft configure -p kvm -m x86_64
4. kraft build
5. kraft run

**Expected behavior**
The error is not descriptive at all, it is more of a python error than something suggestive so you can figure out what to do with kraft. From my point of view, it would be better to suggest to you that kraft doesn't find the executable.

**Screenshots**
![Screenshot from 2021-10-30 10-38-11](https://user-images.githubusercontent.com/34304856/139524725-8bc72103-1d16-4f88-a159-cd5b9de0fb1a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by gabrielmocanu** [comment]
After creating the pull request I was thinking also of something else.
Why don't `kraft build` create by default the unikernel executable as the naming convention from `kraft.yaml`.

So for example:
If we have `app-A`, after `kraft build` we will have the unikernel executable `app-A_x86-64`, even though in the `kraft.yaml` file we have the application name only 'A'. I think it's better to use only the notations from `kraft.yml`.
Is there any consideration of using the directory name of the application for unikernel executable name?

**Comment by gabrielmocanu** [comment]
I create another issue for what I told you before.(#83)
But I think the PR from this issue is still relevant because it basically treats a possible error there.

**Comment by xymeng16** [comment]
#73 is also related to this issue.

**Comment by gabrielmocanu** [comment]
@StefanJum 

Can this issue be closed since this [PR] was merged?

[PR]: https://github.com/unikraft/kraft/pull/94

**Comment by StefanJum** [comment]
> @StefanJum
> 
> Can this issue be closed since this [PR](https://github.com/unikraft/kraft/pull/94) was merged?

Yes, I think it should be closed.
