### ISSUE TITLE
Create application with name from `kraft.yaml`

### ISSUE THREAD

**Issue by gabrielmocanu** [unikraft/kraft#83]
**Describe the bug**
Right now when you build an application it will use the name convention from the parent directory of that application, instead of using the name from `kraft.yaml`. This bug also caused this problem #80 . 

**To Reproduce**
1.git@github.com:unikraft/app-helloworld.git 
2. cd app-helloworold
3. kraft configure -p kvm -m x86_64
4. kraft build

**Expected behavior**
After building an application with the name `example` from `kraft.yaml`, the unikernel executable should have the name `example_kvm-x86-64` even though the parent directory where this application has a different name.

**Screenshots**
![Screenshot from 2021-10-30 13-56-53](https://user-images.githubusercontent.com/34304856/139530124-56c71eaa-d468-420b-a541-092bfeda0f96.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.10

**Additional context**

**Comment by xymeng16** [comment]
#73 is also related to this issue.

**Comment by gabrielmocanu** [comment]
@StefanJum 

Can this issue be closed since this [PR] was merged?

[PR]: https://github.com/unikraft/kraft/pull/94

**Comment by StefanJum** [comment]
> @StefanJum
> 
> Can this issue be closed since this [PR](https://github.com/unikraft/kraft/pull/94) was merged?

Yes, we should close this.
