### ISSUE TITLE
How can I install kraft on Android phones 

### ISSUE THREAD

**Issue by byteshiva** [unikraft/kraft#89]
Will i able to install kraft on Android phones ?

**Comment by byteshiva** [comment]
I see I could use, how do I create one for arm 

```
docker run -it unikraft/kraft list
```

**Comment by nderjung** [comment]
Hi @byteshiva, you are discussing three problems here, I'll try and address them for you:

 * Running `kraft` on Android.  I'm not entirely sure why you would like to do this nor will making this possible be of any immediate priority by any core maintainer.  Generally, `kraft` is intended for a standard developer environment and not for "on-the-go" devices such as phones or tablets. It's probably possible if you hack the device to include necessary dependencies, but this should be left up to you and no support will be provided in this endevaour.
 
 * Running `kraft` on arm-based architectures, such as the M1.  This is a more reasonable goal for `kraft`, as this is a growing architecture used in development environments, such as with the latest Apple Macs.  At the moment, a standard python3, make, binutils and gcc install be neccessary to use `kraft` on arm.  Installing `kraft` via `pip3` (as in the README) and any other depencencies via your local package manager should make this work
 
 * A arm-based Docker build environment.  Similar to the point above but this is a little more abstract: we have a build environment known to work for `x86_64`.  Investigation needs to occur to see how this can be built for arm.  My initial suspicion is that simply running the build script to make the container environment on an arm-based processor will work for 90% of the build.  The last 10% will be able to ensuring that `gcc` builds correctly (maybe additional build parameters are necessary there).

I'm closing this issue as off-topic.  For the last 2 points, separate issues can be opened when necessary.
