### ISSUE TITLE
UTF-8 characters in subprocess output make `kraft configure` crash

### ISSUE THREAD

**Issue by TheLortex** [unikraft/kraft#96]
**Describe the bug**
System configured for French, I tried to follow the example guide and when running `kraft configure` I've got:
```
[CRITICAL] 'ascii' codec can't decode byte 0xc2 in position 4: ordinal not in range(128)
```

**To Reproduce**
1. Configure your system in a language that might make UTF-8 characters in program outputs
2. Run `kraft configure` and select a platform

**Additional context**

It looks like it happens here:
- https://github.com/unikraft/kraft/blob/staging/kraft/util/op.py#L67
- https://github.com/unikraft/kraft/blob/staging/kraft/util/op.py#L143

Instead the text should be decoded as UTF-8. My `make` command output is the following:
```
make : on entre dans le répertoire « /home/lucas/.unikraft/unikraft »
```

**Comment by antkern** [comment]
Same for me :p

Works by setting LANG=EN
