### ISSUE TITLE
`kraft up -t helloworld@staging ./my-first-unikernel` not working as expected

### ISSUE THREAD

**Issue by TheLortex** [unikraft/kraft#97]
**Describe the bug**
`kraft up -t helloworld@staging ./my-first-unikernel` is failing with:
```
.... [makefile logs]
GEN     uk-gdb.py
make : on quitte le répertoire « /home/lucas/.unikraft/unikraft »

Successfully built unikernels:

To instantiate, use: kraft run

[CRITICAL] Could not find unikernel: [...]/./my-first-unikernel/build/helloworld_kvm-x86_64
```

**To Reproduce**
1. System is Fedora 35 x86
2. Run `kraft up -t helloworld@staging ./my-first-unikernel`
3. Observe the failure

**Additional context**
It works correctly if the unikernel name matches the project name, i.e. running:
```
kraft up -t helloworld@staging ./helloworld
```

**Comment by gabrielmocanu** [comment]
Hi, @TheLortex.

Can you try again after updating the `staging` branch?
This PR #94 should have solved the problem.

**Comment by TheLortex** [comment]
All good, thanks !
